---@enum CustomCallback
TSIL.Enums.CustomCallback = {
    MC_POST_SLOT_INIT = 1,
    MC_POST_SLOT_UPDATE = 2,
    MC_POST_SLOT_PRIZE = 3,
    MC_PRE_SLOT_COLLISION = 4,

    MC_POST_PLAYER_COLLECTIBLE_ADDED = 5,
    MC_POST_PLAYER_COLLECTIBLE_REMOVED = 6,

    MC_POST_PLAYER_GULPED_TRINKET_ADDED = 7,
    MC_POST_PLAYER_GULPED_TRINKET_REMOVED = 8,

    MC_POST_GRID_ENTITY_UPDATE = 9,
}