---@enum SlotVariant
TSIL.Enums.SlotVariant = {
    SLOT_MACHINE = 1,
    SLOT_BLOOD_DONATION_MACHINE = 2,
    SLOT_FORTUNE_TELLING_MACHINE = 3,
    SLOT_BEGGAR = 4,
    SLOT_DEVIL_BEGGAR = 5,
    SLOT_SHELL_GAME = 6,
    SLOT_KEY_BEGGAR = 7,
    SLOT_DONATION_MACHINE = 8,
    SLOT_BOMB_BEGGAR = 9,
    SLOT_RESTOCK_MACHINE = 10,
    SLOT_GREED_DONATION_MACHINE = 11,
    SLOT_DRESSING_TABLE = 12,
    SLOT_BATTERY_BEGGAR = 13,
    SLOT_TAINTED_UNLOCK = 14,
    SLOT_HELL_GAME = 15,
    SLOT_CRANE_GAME = 16,
    SLOT_CONFESSIONAL = 17,
    SLOT_ROTTEN_BEGGAR = 18
}