---@enum SlotVariant
TSIL.Enums.SlotVariant = {
    SLOT_MACHINE = 1,
    BLOOD_DONATION_MACHINE = 2,
    FORTUNE_TELLING_MACHINE = 3,
    BEGGAR = 4,
    DEVIL_BEGGAR = 5,
    SHELL_GAME = 6,
    KEY_BEGGAR = 7,
    DONATION_MACHINE = 8,
    BOMB_BEGGAR = 9,
    RESTOCK_MACHINE = 10,
    GREED_DONATION_MACHINE = 11,
    DRESSING_TABLE = 12,
    BATTERY_BEGGAR = 13,
    TAINTED_UNLOCK = 14,
    HELL_GAME = 15,
    CRANE_GAME = 16,
    CONFESSIONAL = 17,
    ROTTEN_BEGGAR = 18
}